### PR TITLE
Add friture icon

### LINKED ISSUE #3: Icon: cuisine=friture
I think it would be nice to replace the default icon for `amenity=fast_food` when `cuisine=friture`.

Something like this : https://www.iconfinder.com/icons/189409/food_french_fries_vegetable_icon

**Could someone create such an icon ?**

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3

friture

screenshot_2018-05-11_18-46-52
Location: https://www.openstreetmap.org/#map=18/51.31298/3.12389

### CODE REVIEW

**Comment by ghost** [comment]
I'm not entirely convinced of the icon, it feels a bit out of place. Let me know what you think.

**Comment by jbelien** [comment]
Awesome !!!

Thank you so much @M1dgard \o/

**Comment by ghost** [comment]
You know you have to merge this if you want to use this icon, right?

**Comment by jbelien** [comment]
@M1dgard Hahaha ... Yes, I know how GitHub works :P

**Comment by ghost** [comment]
Just saying, because you were so enthusiastic but didn't merge it ;)

**Comment by jbelien** [comment]
I'll try to merge it tomorrow :)

**Comment by ghost** [comment]
Heads up: I am going to delete my GitHub account in a few days to prepare for Microsoft's GitHub acquisition. If this PR isn't merged, or copied to a separate branch on your project, its code will be inaccessible.

**Comment by jbelien** [comment]
Thanks for the heads up.

I merged it ; 
Will be rendered next update (not sure when exactly but I'll keep you updated of course) !

**Pull request merged**
