### PR TITLE
Basic flowers, first test

### PR DESCRIPTION
**Pull request by pietervdvn**
Lets not be hasty, but patterns and more colors are planned next!

### CODE REVIEW

**Comment by jbelien** [comment]
Looks good ! 👍

**Comment by jbelien** [comment]
Place to check : https://www.openstreetmap.org/#map=18/51.02041/4.46250

**Comment by jbelien** [comment]
Good idea the playgrounds ^^
But again, could you separate flowers from playgrounds ? Thanks :)

**Comment by pietervdvn** [comment]
Oh, god damn it. Are those added on the flower branch as well?

Will look into it tomorrow.


Met vriendelijke groeten,
Pieter Vander Vennet

2018-03-29 22:26 GMT+02:00 Jonathan Beliën <notifications@github.com>:

**Comment by jbelien** [comment]
> Oh, god damn it. Are those added on the flower branch as well?

Yes, they are ^^
You need to create a new `branch` for every new feature to avoid this to happen !

**Review by jbelien — CHANGES_REQUESTED** [review]
Hey @pietervdvn , could you remove everything related to playgrounds from this PR so we have a clean PR ?

Thanks :)

**Pull request closed without merging**
